// import 'bootstrap-less/js/affix.js'
// import 'bootstrap-less/js/alert.js'
// import 'bootstrap-less/js/button.js'
// import 'bootstrap-less/js/carousel.js'
import 'bootstrap-less/js/collapse.js'
// import 'bootstrap-less/js/dropdown.js'
// import 'bootstrap-less/js/modal.js'
// import 'bootstrap-less/js/tooltip.js'
// import 'bootstrap-less/js/popover.js'
// import 'bootstrap-less/js/scrollspy.js'
// import 'bootstrap-less/js/tab.js'
import 'bootstrap-less/js/transition.js'
